CREATE TABLE accounts (
idAccount INT NOT NULL AUTO_INCREMENT,
netid VARCHAR(7) NOT NULL UNIQUE,
password VARCHAR(63) NOT NULL,
firstName VARCHAR(15) NOT NULL,
lastName VARCHAR(15) NOT NULL,
phone VARCHAR(16) NOT NULL,
PRIMARY KEY (idAccount)
);
